"""automatic migration

Revision ID: 08bf96dd5ca7
Revises: 69bcaa0c2744
Create Date: 2022-06-18 14:47:31.762071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08bf96dd5ca7'
down_revision = '69bcaa0c2744'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('projects_contents', sa.Column('delta_rail_km_rail', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('delta_rail_km_car_to_rail', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('delta_rail_km_rail_to_car', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('delta_rail_km_air_to_rail', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('delta_rail_km_induced', sa.Float(), nullable=True))
    # op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost', sa.Float(), nullable=True))
    op.drop_column('projects_contents', 'delta_km_car_to_rail')
    op.drop_column('projects_contents', 'delta_km_rail_to_car')
    op.drop_column('projects_contents', 'delta_km_air_to_rail')
    # op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos')
    op.drop_column('projects_contents', 'delta_km_induced')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_contents', sa.Column('delta_km_induced', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects_contents', sa.Column('delta_km_air_to_rail', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects_contents', sa.Column('delta_km_rail_to_car', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects_contents', sa.Column('delta_km_car_to_rail', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost')
    op.drop_column('projects_contents', 'delta_rail_km_induced')
    op.drop_column('projects_contents', 'delta_rail_km_air_to_rail')
    op.drop_column('projects_contents', 'delta_rail_km_rail_to_car')
    op.drop_column('projects_contents', 'delta_rail_km_car_to_rail')
    op.drop_column('projects_contents', 'delta_rail_km_rail')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

