"""automatic migration

Revision ID: 08e863a780ec
Revises: 9e1466c7cd21
Create Date: 2024-01-10 09:23:41.977436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e863a780ec'
down_revision = '9e1466c7cd21'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('finve_to_projectcontent_pc_id_fkey', 'finve_to_projectcontent', type_='foreignkey')
    op.drop_constraint('finve_to_projectcontent_finve_id_fkey', 'finve_to_projectcontent', type_='foreignkey')
    op.create_foreign_key(None, 'finve_to_projectcontent', 'projects_contents', ['pc_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'finve_to_projectcontent', 'finve', ['finve_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('nodes_to_routes_node_id_fkey', 'nodes_to_routes', type_='foreignkey')
    op.drop_constraint('nodes_to_routes_route_id_fkey', 'nodes_to_routes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes_to_routes', 'railway_nodes', ['node_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'nodes_to_routes', 'railway_route', ['route_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('projectcontent_to_constituencies_project_content_id_fkey', 'projectcontent_to_constituencies', type_='foreignkey')
    op.drop_constraint('projectcontent_to_constituencies_constituencies_id_fkey', 'projectcontent_to_constituencies', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_constituencies', 'projects_contents', ['project_content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'projectcontent_to_constituencies', 'constituencies', ['constituencies_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('projectcontent_to_counties_project_content_id_fkey', 'projectcontent_to_counties', type_='foreignkey')
    op.drop_constraint('projectcontent_to_counties_counties_id_fkey', 'projectcontent_to_counties', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_counties', 'counties', ['counties_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'projectcontent_to_counties', 'projects_contents', ['project_content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('projectcontent_to_lines_projects_contents_id_fk', 'projectcontent_to_lines', type_='foreignkey')
    op.drop_constraint('projectcontent_to_lines_railway_lines_id_fkey', 'projectcontent_to_lines', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_lines', 'projects_contents', ['projectcontent_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'projectcontent_to_lines', 'railway_lines', ['railway_lines_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('projectcontent_to_railwaystations_railway_station_id_fkey', 'projectcontent_to_railwaystations', type_='foreignkey')
    op.drop_constraint('projectcontent_to_railwaystations_projectcontent_id_fkey', 'projectcontent_to_railwaystations', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_railwaystations', 'projects_contents', ['projectcontent_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'projectcontent_to_railwaystations', 'railway_stations', ['railway_station_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('projectcontent_to_states_project_content_id_fkey', 'projectcontent_to_states', type_='foreignkey')
    op.drop_constraint('projectcontent_to_states_states_id_fkey', 'projectcontent_to_states', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_states', 'states', ['states_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'projectcontent_to_states', 'projects_contents', ['project_content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('texts_to_projects_text_id_fkey', 'texts_to_projects', type_='foreignkey')
    op.drop_constraint('texts_to_projects_project_content_id_fkey', 'texts_to_projects', type_='foreignkey')
    op.create_foreign_key(None, 'texts_to_projects', 'projects_contents', ['project_content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'texts_to_projects', 'texts', ['text_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts_to_projects', type_='foreignkey')
    op.drop_constraint(None, 'texts_to_projects', type_='foreignkey')
    op.create_foreign_key('texts_to_projects_project_content_id_fkey', 'texts_to_projects', 'projects_contents', ['project_content_id'], ['id'])
    op.create_foreign_key('texts_to_projects_text_id_fkey', 'texts_to_projects', 'texts', ['text_id'], ['id'])
    op.drop_constraint(None, 'projectcontent_to_states', type_='foreignkey')
    op.drop_constraint(None, 'projectcontent_to_states', type_='foreignkey')
    op.create_foreign_key('projectcontent_to_states_states_id_fkey', 'projectcontent_to_states', 'states', ['states_id'], ['id'])
    op.create_foreign_key('projectcontent_to_states_project_content_id_fkey', 'projectcontent_to_states', 'projects_contents', ['project_content_id'], ['id'])
    op.drop_constraint(None, 'projectcontent_to_railwaystations', type_='foreignkey')
    op.drop_constraint(None, 'projectcontent_to_railwaystations', type_='foreignkey')
    op.create_foreign_key('projectcontent_to_railwaystations_projectcontent_id_fkey', 'projectcontent_to_railwaystations', 'projects_contents', ['projectcontent_id'], ['id'])
    op.create_foreign_key('projectcontent_to_railwaystations_railway_station_id_fkey', 'projectcontent_to_railwaystations', 'railway_stations', ['railway_station_id'], ['id'])
    op.drop_constraint(None, 'projectcontent_to_lines', type_='foreignkey')
    op.drop_constraint(None, 'projectcontent_to_lines', type_='foreignkey')
    op.create_foreign_key('projectcontent_to_lines_railway_lines_id_fkey', 'projectcontent_to_lines', 'railway_lines', ['railway_lines_id'], ['id'])
    op.create_foreign_key('projectcontent_to_lines_projects_contents_id_fk', 'projectcontent_to_lines', 'projects_contents', ['projectcontent_id'], ['id'])
    op.drop_constraint(None, 'projectcontent_to_counties', type_='foreignkey')
    op.drop_constraint(None, 'projectcontent_to_counties', type_='foreignkey')
    op.create_foreign_key('projectcontent_to_counties_counties_id_fkey', 'projectcontent_to_counties', 'counties', ['counties_id'], ['id'])
    op.create_foreign_key('projectcontent_to_counties_project_content_id_fkey', 'projectcontent_to_counties', 'projects_contents', ['project_content_id'], ['id'])
    op.drop_constraint(None, 'projectcontent_to_constituencies', type_='foreignkey')
    op.drop_constraint(None, 'projectcontent_to_constituencies', type_='foreignkey')
    op.create_foreign_key('projectcontent_to_constituencies_constituencies_id_fkey', 'projectcontent_to_constituencies', 'constituencies', ['constituencies_id'], ['id'])
    op.create_foreign_key('projectcontent_to_constituencies_project_content_id_fkey', 'projectcontent_to_constituencies', 'projects_contents', ['project_content_id'], ['id'])
    op.drop_constraint(None, 'nodes_to_routes', type_='foreignkey')
    op.drop_constraint(None, 'nodes_to_routes', type_='foreignkey')
    op.create_foreign_key('nodes_to_routes_route_id_fkey', 'nodes_to_routes', 'railway_route', ['route_id'], ['id'])
    op.create_foreign_key('nodes_to_routes_node_id_fkey', 'nodes_to_routes', 'railway_nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'finve_to_projectcontent', type_='foreignkey')
    op.drop_constraint(None, 'finve_to_projectcontent', type_='foreignkey')
    op.create_foreign_key('finve_to_projectcontent_finve_id_fkey', 'finve_to_projectcontent', 'finve', ['finve_id'], ['id'])
    op.create_foreign_key('finve_to_projectcontent_pc_id_fkey', 'finve_to_projectcontent', 'projects_contents', ['pc_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

