"""automatic migration

Revision ID: 0a11b530d943
Revises: 623e0007ca8d
Create Date: 2022-06-20 15:18:17.544133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a11b530d943'
down_revision = '623e0007ca8d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost', sa.Float(), nullable=True))
    # op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos')
    op.add_column('railway_route', sa.Column('start_km', sa.Float(), nullable=True))
    op.add_column('railway_route', sa.Column('end_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('railway_route', 'end_km')
    op.drop_column('railway_route', 'start_km')
    op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

