"""automatic migration

Revision ID: 0be98595eab3
Revises: 2271b76c4cbe
Create Date: 2022-09-01 10:27:59.926962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be98595eab3'
down_revision = '2271b76c4cbe'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_train_groups',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('train_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('railml_ocps',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('operational_type', sa.String(length=31), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['railway_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_train_parts',
    sa.Column('id', sa.String(length=510), nullable=False),
    sa.Column('category_id', sa.String(length=15), nullable=True),
    sa.Column('formation_id', sa.String(length=100), nullable=True),
    sa.Column('operating_period_id', sa.String(length=31), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['timetable_categories.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['operating_period_id'], ['timetable_operating_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_ocps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_part', sa.String(length=510), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('ocp_id', sa.String(length=255), nullable=True),
    sa.Column('stop_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ocp_id'], ['railml_ocps.id'], ),
    sa.ForeignKeyConstraint(['train_part'], ['timetable_train_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_train',
    sa.Column('id', sa.String(length=510), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('train_number', sa.Integer(), nullable=True),
    sa.Column('train_group_id', sa.String(length=255), nullable=True),
    sa.Column('line_number', sa.String(length=255), nullable=True),
    sa.Column('train_validity_name', sa.String(length=255), nullable=True),
    sa.Column('train_part_id', sa.String(length=510), nullable=True),
    sa.Column('speed_profile_ref', sa.String(length=255), nullable=True),
    sa.Column('brake_type', sa.String(length=255), nullable=True),
    sa.Column('air_brake_application_position', sa.String(length=255), nullable=True),
    sa.Column('regular_brake_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['train_group_id'], ['timetable_train_groups.id'], ),
    sa.ForeignKeyConstraint(['train_part_id'], ['timetable_train_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timetable_ocp_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('line', sa.String(length=255), nullable=True),
    sa.Column('track_id', sa.String(length=510), nullable=True),
    sa.Column('direction', sa.String(length=15), nullable=True),
    sa.Column('minimal_run_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_ocp_id'], ['timetable_ocps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timetable_ocp_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('arrival', sa.Time(), nullable=True),
    sa.Column('departure', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_ocp_id'], ['timetable_ocps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('timetable_times')
    op.drop_table('timetable_sections')
    op.drop_table('timetable_train')
    op.drop_table('timetable_ocps')
    op.drop_table('timetable_train_parts')
    op.drop_table('railml_ocps')
    op.drop_table('timetable_train_groups')
    # ### end Alembic commands ###

