"""automatic migration

Revision ID: 100c7a951568
Revises: 5b0a91c2988e
Create Date: 2024-08-22 11:19:54.847928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100c7a951568'
down_revision = '5b0a91c2988e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('bks_action', sa.Column('review_2_start', sa.Text(), nullable=True))
    op.add_column('bks_action', sa.Column('review_2_done', sa.Text(), nullable=True))
    op.add_column('bks_action', sa.Column('review_2_next', sa.Text(), nullable=True))
    op.add_column('bks_action', sa.Column('review_2_status', sa.String(length=255), nullable=True))
    op.add_column('bks_action', sa.Column('review_2_changed_aim', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bks_action', 'review_2_changed_aim')
    op.drop_column('bks_action', 'review_2_status')
    op.drop_column('bks_action', 'review_2_next')
    op.drop_column('bks_action', 'review_2_done')
    op.drop_column('bks_action', 'review_2_start')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

