"""automatic migration

Revision ID: 11a99a7b022a
Revises: f1c5906cbe89
Create Date: 2022-07-02 12:03:08.123612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11a99a7b022a'
down_revision = 'f1c5906cbe89'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost', sa.Float(), nullable=True))
    # op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos')
    op.drop_constraint('railway_lines_end_node_fkey', 'railway_lines', type_='foreignkey')
    op.drop_constraint('railway_lines_start_node_fkey', 'railway_lines', type_='foreignkey')
    op.create_foreign_key(None, 'railway_lines', 'railway_nodes', ['start_node'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'railway_lines', 'railway_nodes', ['end_node'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'railway_lines', type_='foreignkey')
    op.drop_constraint(None, 'railway_lines', type_='foreignkey')
    op.create_foreign_key('railway_lines_start_node_fkey', 'railway_lines', 'railway_nodes', ['start_node'], ['id'])
    op.create_foreign_key('railway_lines_end_node_fkey', 'railway_lines', 'railway_nodes', ['end_node'], ['id'])
    op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

