"""even more relations and table budget

Revision ID: 174ba62c6afa
Revises: 9a0b3cccefca
Create Date: 2022-04-07 11:41:50.818079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174ba62c6afa'
down_revision = '9a0b3cccefca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_content_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('spent_cost_two_years_before', sa.Integer(), nullable=True),
    sa.Column('allowed_year_before', sa.Integer(), nullable=True),
    sa.Column('delegated_costs', sa.Integer(), nullable=True),
    sa.Column('planned_cost_this_year', sa.Integer(), nullable=True),
    sa.Column('planned_cost_next_year', sa.Integer(), nullable=True),
    sa.Column('planned_cost_following_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    op.add_column('projects_contents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('projects_contents', sa.Column('lfd_nr', sa.Integer(), nullable=True))
    op.add_column('projects_contents', sa.Column('finve_nr', sa.Integer(), nullable=True))
    op.add_column('projects_contents', sa.Column('bedarfsplan_nr', sa.Integer(), nullable=True))
    op.add_column('projects_contents', sa.Column('planned_total_cost', sa.Integer(), nullable=True))
    op.add_column('projects_contents', sa.Column('actual_cost', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects_contents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects_contents', type_='foreignkey')
    op.drop_column('projects_contents', 'actual_cost')
    op.drop_column('projects_contents', 'planned_total_cost')
    op.drop_column('projects_contents', 'bedarfsplan_nr')
    op.drop_column('projects_contents', 'finve_nr')
    op.drop_column('projects_contents', 'lfd_nr')
    op.drop_column('projects_contents', 'project_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('budget')
    # ### end Alembic commands ###
