"""automatic migration

Revision ID: 1e1eaf409857
Revises: f9b905675c5d
Create Date: 2022-06-11 16:08:51.624793

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1e1eaf409857'
down_revision = 'f9b905675c5d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('projectcontent_to_group_projectcontent_id_fkey', 'projectcontent_to_group', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_group', 'projects_contents', ['projectcontent_id'], ['id'])
    op.drop_constraint('projects_to_lines_railway_lines_id_fkey', 'projectcontent_to_lines', type_='foreignkey')
    op.create_foreign_key(None, 'projectcontent_to_lines', 'railway_lines', ['railway_lines_id'], ['id'])
    op.drop_constraint('projects_contents_project_id_fkey', 'projects_contents', type_='foreignkey')
    op.create_foreign_key(None, 'projects_contents', 'projects', ['project_id'], ['id'])
    op.alter_column('railway_lines', 'coordinates',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=False)
    op.create_index('idx_railway_lines_coordinates', 'railway_lines', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_railway_lines_coordinates', table_name='railway_lines', postgresql_using='gist', postgresql_ops={})
    op.alter_column('railway_lines', 'coordinates',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True)
    op.drop_constraint(None, 'projects_contents', type_='foreignkey')
    op.create_foreign_key('projects_contents_project_id_fkey', 'projects_contents', 'projects', ['project_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'projectcontent_to_lines', type_='foreignkey')
    op.create_foreign_key('projects_to_lines_railway_lines_id_fkey', 'projectcontent_to_lines', 'railway_lines', ['railway_lines_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'projectcontent_to_group', type_='foreignkey')
    op.create_foreign_key('projectcontent_to_group_projectcontent_id_fkey', 'projectcontent_to_group', 'projects_contents', ['projectcontent_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    """
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    """
    # ### end Alembic commands ###

