"""first m:n and other stuff

Revision ID: 23657ae99b26
Revises: 174ba62c6afa
Create Date: 2022-04-07 12:05:35.976674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23657ae99b26'
down_revision = '174ba62c6afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_to_group',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('projectgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['projectgroup_id'], ['project_groups.id'], )
    )
    #op.drop_table('spatial_ref_sys')
    op.add_column('projects', sa.Column('ProjectGroup', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'project_groups', ['ProjectGroup'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'ProjectGroup')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('project_to_group')
    op.drop_table('text')
    op.drop_table('project_groups')
    # ### end Alembic commands ###
