"""automatic migration

Revision ID: 27897879bc1d
Revises: a59881c5015c
Create Date: 2022-06-12 15:38:59.909223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27897879bc1d'
down_revision = 'a59881c5015c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_short_2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectcontent_to_states',
    sa.Column('project_content_id', sa.Integer(), nullable=True),
    sa.Column('states_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], ),
    sa.ForeignKeyConstraint(['states_id'], ['states.id'], )
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column('projects_contents', sa.Column('reason_project', sa.Text(), nullable=True))
    op.add_column('projects_contents', sa.Column('reason_priority', sa.Text(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_environmental_impact', sa.String(length=200), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_planned_planning_cost', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_planned_planning_cost_incurred', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_total_budget_relevant_cost', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_total_budget_relevant_cost_incurred', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_regional_significance', sa.String(length=255), nullable=True))
    op.add_column('projects_contents', sa.Column('bottleneck_elimination', sa.Boolean(), nullable=True))
    op.add_column('projects_contents', sa.Column('traveltime_reduction', sa.Float(), nullable=True))
    op.add_column('texts_to_projects', sa.Column('text_id', sa.Integer(), nullable=True))
    op.drop_constraint('texts_to_projects_text.id_fkey', 'texts_to_projects', type_='foreignkey')
    op.create_foreign_key(None, 'texts_to_projects', 'texts', ['text_id'], ['id'])
    op.drop_column('texts_to_projects', 'text.id')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts_to_projects', sa.Column('text.id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'texts_to_projects', type_='foreignkey')
    op.create_foreign_key('texts_to_projects_text.id_fkey', 'texts_to_projects', 'texts', ['text.id'], ['id'])
    op.drop_column('texts_to_projects', 'text_id')
    op.drop_column('projects_contents', 'traveltime_reduction')
    op.drop_column('projects_contents', 'bottleneck_elimination')
    op.drop_column('projects_contents', 'bvwp_regional_significance')
    op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012')
    op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost')
    op.drop_column('projects_contents', 'bvwp_total_budget_relevant_cost_incurred')
    op.drop_column('projects_contents', 'bvwp_total_budget_relevant_cost')
    op.drop_column('projects_contents', 'bvwp_planned_planning_cost_incurred')
    op.drop_column('projects_contents', 'bvwp_planned_planning_cost')
    op.drop_column('projects_contents', 'bvwp_environmental_impact')
    op.drop_column('projects_contents', 'reason_priority')
    op.drop_column('projects_contents', 'reason_project')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('projectcontent_to_states')
    op.drop_table('states')
    # ### end Alembic commands ###

