"""automatic migration

Revision ID: 2d6d2b1813e3
Revises: 75e8093f05a9
Create Date: 2022-06-18 11:41:47.529615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6d2b1813e3'
down_revision = '75e8093f05a9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('projects_contents', sa.Column('bvwp_alternatives', sa.Text(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_6to9_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_6to9_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_6to9_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_6to9_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_9to16_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_9to16_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_9to16_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_9to16_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_16to19_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_16to19_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_16to19_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_16to19_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_19to22_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_19to22_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_19to22_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_19to22_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_22to6_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_22to6_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_22to6_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_22to6_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_day_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_reference_day_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_day_km', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_congested_rail_plancase_day_perc', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_unscheduled_waiting_period_reference', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_unscheduled_waiting_period_plancase', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_punctuality_cargo_reference', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_delta_punctuality_realitv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_delta_punctuality_absolut', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('bvwp_traveltime_examples', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_contents', 'bvwp_traveltime_examples')
    op.drop_column('projects_contents', 'bvwp_delta_punctuality_absolut')
    op.drop_column('projects_contents', 'bvwp_delta_punctuality_realitv')
    op.drop_column('projects_contents', 'bvwp_punctuality_cargo_reference')
    op.drop_column('projects_contents', 'bvwp_unscheduled_waiting_period_plancase')
    op.drop_column('projects_contents', 'bvwp_unscheduled_waiting_period_reference')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_day_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_day_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_day_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_day_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_22to6_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_22to6_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_22to6_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_22to6_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_19to22_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_19to22_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_19to22_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_19to22_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_16to19_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_16to19_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_16to19_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_16to19_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_9to16_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_9to16_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_9to16_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_9to16_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_6to9_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_plancase_6to9_km')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_6to9_perc')
    op.drop_column('projects_contents', 'bvwp_congested_rail_reference_6to9_km')
    op.drop_column('projects_contents', 'bvwp_alternatives')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

