"""empty message

Revision ID: 2edfaf82b56e
Revises: 
Create Date: 2022-04-06 18:53:20.589160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edfaf82b56e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mifcode', sa.Integer(), nullable=True),
    sa.Column('streckennummer', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('from_km', sa.Integer(), nullable=True),
    sa.Column('to_km', sa.Integer(), nullable=True),
    sa.Column('electrified', sa.String(length=20), nullable=True),
    sa.Column('number_tracks', sa.Integer(), nullable=True),
    sa.Column('vmax', sa.String(length=20), nullable=True),
    sa.Column('type_of_transport', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('railway_line')
    # ### end Alembic commands ###
