"""automatic migration

Revision ID: 3019899bbe08
Revises: 8626e8908706
Create Date: 2024-01-24 12:46:18.441072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3019899bbe08'
down_revision = '8626e8908706'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('netzzustandsbericht', sa.Column('hlk', sa.Boolean(), nullable=True))
    op.drop_constraint('netzzustandsbericht_year_key', 'netzzustandsbericht', type_='unique')
    op.create_unique_constraint('unique_netzzustand', 'netzzustandsbericht', ['year', 'hlk'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_netzzustand', 'netzzustandsbericht', type_='unique')
    op.create_unique_constraint('netzzustandsbericht_year_key', 'netzzustandsbericht', ['year'])
    op.drop_column('netzzustandsbericht', 'hlk')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

