"""automatic migration

Revision ID: 329ffb153d98
Revises: 100c7a951568
Create Date: 2024-09-02 10:38:31.384774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329ffb153d98'
down_revision = '100c7a951568'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_to_projectcontent',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pc_id'], ['projects_contents.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'pc_id'),
    sa.UniqueConstraint('budget_id', 'pc_id', name='unique_budget_pc')
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column('budgets', sa.Column('sammel_finve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'sammel_finve')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('budget_to_projectcontent')
    # ### end Alembic commands ###

