"""automatic migration

Revision ID: 3692d09a8444
Revises: a58533c703dc
Create Date: 2023-10-30 16:31:39.992973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3692d09a8444'
down_revision = 'a58533c703dc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('bks', sa.Column('cluster_number', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'bks', 'bks_cluster', ['cluster_number'], ['number'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('bks_cluster', sa.Column('handlungsfeld_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bks_cluster', 'bks_handlungsfeld', ['handlungsfeld_id'], ['number'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bks_cluster', type_='foreignkey')
    op.drop_column('bks_cluster', 'handlungsfeld_id')
    op.drop_constraint(None, 'bks', type_='foreignkey')
    op.drop_column('bks', 'cluster_number')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

