"""automatic migration

Revision ID: 42e346cb4d2a
Revises: 9c4f0bfd291a
Create Date: 2022-09-10 20:49:00.647191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e346cb4d2a'
down_revision = '9c4f0bfd291a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles_pattern',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_of_traction', sa.String(length=255), nullable=False),
    sa.Column('wagons_of_trainset', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('traction', sa.Integer(), nullable=True),
    sa.Column('speed_max', sa.Integer(), nullable=True),
    sa.Column('tilting', sa.Boolean(), nullable=True),
    sa.Column('couple_allowed', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('investment_cost', sa.Float(), nullable=True),
    sa.Column('debt_service', sa.Float(), nullable=True),
    sa.Column('maintenance_cost_km', sa.Float(), nullable=True, comment='per vehicle-km'),
    sa.Column('maintenance_cost_hour', sa.Float(), nullable=True),
    sa.Column('train_driver_cost', sa.Float(), nullable=True, comment='per vehicle-hour'),
    sa.Column('head_of_train_cost', sa.Float(), nullable=True, comment='per vehicle-hour'),
    sa.Column('energy_per_km', sa.Float(), nullable=True, comment='kWh/vehicle-km'),
    sa.Column('energy_abs_per_km', sa.Float(), nullable=True),
    sa.Column('energy_nbs_per_km', sa.Float(), nullable=True),
    sa.Column('fuel_consumption_diesel_km', sa.Float(), nullable=True),
    sa.Column('fuel_consumption_h2_km', sa.Float(), nullable=True),
    sa.Column('energy_consumption_hour', sa.Float(), nullable=True),
    sa.Column('fuel_consumption_diesel_hour', sa.Float(), nullable=True),
    sa.Column('fuel_consumption_h2_hour', sa.Float(), nullable=True),
    sa.Column('energy_stop_a', sa.Float(), nullable=True),
    sa.Column('energy_stop_b', sa.Float(), nullable=True),
    sa.Column('emission_production_vehicle', sa.Float(), nullable=True, comment='kg CO2/Leermasse * Jahr'),
    sa.Column('additional_energy_without_overhead', sa.Float(), nullable=True),
    sa.Column('additional_maintenance_cost_withou_overhead', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column('vehicles', sa.Column('vehicle_pattern_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'vehicles_pattern', ['vehicle_pattern_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'vehicle_pattern_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('vehicles_pattern')
    # ### end Alembic commands ###

