"""empty message

Revision ID: 4ec67bbe5d13
Revises: c82896bc3110
Create Date: 2023-01-07 15:16:29.313359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ec67bbe5d13'
down_revision = 'c82896bc3110'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('budgets_year_and_finve_uindex', table_name='budgets')
    op.add_column('formations', sa.Column('formation_id_calculation_bvwp', sa.String(length=100), nullable=True))
    op.add_column('formations', sa.Column('formation_id_calculation_standi', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'formations', 'formations', ['formation_id_calculation_bvwp'], ['id'])
    op.create_foreign_key(None, 'formations', 'formations', ['formation_id_calculation_standi'], ['id'])
    # op.alter_column('railway_lines', 'voltage',
    #            existing_type=postgresql.DOUBLE_PRECISION(precision=53),
    #            comment=None,
    #            existing_comment='[kV]',
    #            existing_nullable=True)
    op.drop_column('timetable_train_groups', 'cost_h2')
    op.drop_column('timetable_train_groups', 'cost_efuel')
    op.drop_column('timetable_train_groups', 'cost_electro_conv')
    op.drop_column('timetable_train_groups', 'cost_electro_renew')
    op.drop_column('timetable_train_groups', 'cost_battery')
    op.drop_column('timetable_train_groups', 'cost_diesel')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_train_groups', sa.Column('cost_diesel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_train_groups', sa.Column('cost_battery', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_train_groups', sa.Column('cost_electro_renew', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_train_groups', sa.Column('cost_electro_conv', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_train_groups', sa.Column('cost_efuel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_train_groups', sa.Column('cost_h2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('railway_lines', 'voltage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='[kV]',
               existing_nullable=True)
    op.drop_constraint(None, 'formations', type_='foreignkey')
    op.drop_constraint(None, 'formations', type_='foreignkey')
    op.drop_column('formations', 'formation_id_calculation_standi')
    op.drop_column('formations', 'formation_id_calculation_bvwp')
    op.create_index('budgets_year_and_finve_uindex', 'budgets', ['budget_year', 'fin_ve'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

