"""empty message

Revision ID: 51fe948ca3a2
Revises: 2edfaf82b56e
Create Date: 2022-04-06 18:59:31.987978

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = '51fe948ca3a2'
down_revision = '2edfaf82b56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('railway_line', sa.Column('coordinates', Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_railway_line_coordinates', 'railway_line', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_railway_line_coordinates', table_name='railway_line', postgresql_using='gist', postgresql_ops={})
    op.drop_column('railway_line', 'coordinates')
    # ### end Alembic commands ###
