"""automatic migration

Revision ID: 5b0a91c2988e
Revises: 7ced9e349daa
Create Date: 2024-02-24 21:25:39.846672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0a91c2988e'
down_revision = '7ced9e349daa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.create_unique_constraint('unique_finve_pc', 'finve_to_projectcontent', ['finve_id', 'pc_id'])
    op.create_unique_constraint('unique_pc_masterscenario', 'pc_to_masterscenario', ['projectcontent_id', 'masterscenario_id'])
    op.create_unique_constraint('unique_pc_constituencies', 'projectcontent_to_constituencies', ['project_content_id', 'constituencies_id'])
    op.create_unique_constraint('unique_pc_states', 'projectcontent_to_states', ['project_content_id', 'states_id'])
    op.create_unique_constraint('unique_bridge_line', 'rwbridges_to_rwlines', ['rw_bridges_id', 'rw_lines_id'])
    op.create_unique_constraint('unique_pc_text', 'texts_to_projects', ['project_content_id', 'text_id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_pc_text', 'texts_to_projects', type_='unique')
    op.drop_constraint('unique_bridge_line', 'rwbridges_to_rwlines', type_='unique')
    op.drop_constraint('unique_pc_states', 'projectcontent_to_states', type_='unique')
    op.drop_constraint('unique_pc_constituencies', 'projectcontent_to_constituencies', type_='unique')
    op.drop_constraint('unique_pc_masterscenario', 'pc_to_masterscenario', type_='unique')
    op.drop_constraint('unique_finve_pc', 'finve_to_projectcontent', type_='unique')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

