"""automatic migration

Revision ID: 5cbd0aeba086
Revises: 7976dc846607
Create Date: 2022-11-20 19:10:04.283677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cbd0aeba086'
down_revision = '7976dc846607'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('budgets_year_and_finve_uindex', table_name='budgets')
    op.drop_constraint('projects_superior_project_content_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'projects_contents', ['superior_project_content_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.drop_constraint('projects_contents_project_id_fkey', 'projects_contents', type_='foreignkey')
    op.create_foreign_key(None, 'projects_contents', 'projects', ['project_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # op.alter_column('railway_lines', 'voltage',
    #            existing_type=postgresql.DOUBLE_PRECISION(precision=53),
    #            comment=None,
    #            existing_comment='[kV]',
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('railway_lines', 'voltage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='[kV]',
               existing_nullable=True)
    op.drop_constraint(None, 'projects_contents', type_='foreignkey')
    op.create_foreign_key('projects_contents_project_id_fkey', 'projects_contents', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_superior_project_content_id_fkey', 'projects', 'projects_contents', ['superior_project_content_id'], ['id'])
    op.create_index('budgets_year_and_finve_uindex', 'budgets', ['budget_year', 'fin_ve'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

