"""empty message

Revision ID: 5e1c99a1a201
Revises: 7867f17d0217
Create Date: 2023-04-09 16:53:01.570933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c99a1a201'
down_revision = '7867f17d0217'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('master_areas', sa.Column('traction_minimal_cost', sa.String(length=255), nullable=True))
    op.add_column('master_areas', sa.Column('cost_efuel', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('cost_diesel', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('cost_h2', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('cost_battery', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('cost_electrification', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('cost_optimised_electrification', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('operating_cost_efuel', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('operating_cost_diesel', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('operating_cost_h2', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('operating_cost_battery', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('operating_cost_electrification', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('operating_cost_optimised_electrification', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('infrastructure_cost_efuel', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('infrastructure_cost_diesel', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('infrastructure_cost_h2', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('infrastructure_cost_battery', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('infrastructure_cost_electrification', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('infrastructure_cost_optimised_electrification', sa.Integer(), nullable=True))
    op.add_column('master_areas', sa.Column('sgv', sa.Boolean(), nullable=True))
    op.add_column('master_areas', sa.Column('spnv', sa.Boolean(), nullable=True))
    op.add_column('master_areas', sa.Column('spfv', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_areas', 'spfv')
    op.drop_column('master_areas', 'spnv')
    op.drop_column('master_areas', 'sgv')
    op.drop_column('master_areas', 'infrastructure_cost_optimised_electrification')
    op.drop_column('master_areas', 'infrastructure_cost_electrification')
    op.drop_column('master_areas', 'infrastructure_cost_battery')
    op.drop_column('master_areas', 'infrastructure_cost_h2')
    op.drop_column('master_areas', 'infrastructure_cost_diesel')
    op.drop_column('master_areas', 'infrastructure_cost_efuel')
    op.drop_column('master_areas', 'operating_cost_optimised_electrification')
    op.drop_column('master_areas', 'operating_cost_electrification')
    op.drop_column('master_areas', 'operating_cost_battery')
    op.drop_column('master_areas', 'operating_cost_h2')
    op.drop_column('master_areas', 'operating_cost_diesel')
    op.drop_column('master_areas', 'operating_cost_efuel')
    op.drop_column('master_areas', 'cost_optimised_electrification')
    op.drop_column('master_areas', 'cost_electrification')
    op.drop_column('master_areas', 'cost_battery')
    op.drop_column('master_areas', 'cost_h2')
    op.drop_column('master_areas', 'cost_diesel')
    op.drop_column('master_areas', 'cost_efuel')
    op.drop_column('master_areas', 'traction_minimal_cost')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

