"""automatic migration

Revision ID: 75e8093f05a9
Revises: 7abed1535286
Create Date: 2022-06-17 12:05:52.320860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e8093f05a9'
down_revision = '7abed1535286'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectcontent_to_constituencies',
    sa.Column('project_content_id', sa.Integer(), nullable=True),
    sa.Column('constituencies_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constituencies_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], )
    )
    op.create_table('projectcontent_to_counties',
    sa.Column('project_content_id', sa.Integer(), nullable=True),
    sa.Column('counties_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counties_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], )
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('projectcontent_to_counties')
    op.drop_table('projectcontent_to_constituencies')
    # ### end Alembic commands ###

