"""empty message

Revision ID: 7867f17d0217
Revises: fed23c93b1e0
Create Date: 2023-04-09 16:01:47.233742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7867f17d0217'
down_revision = 'fed23c93b1e0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('master_scenarios', sa.Column('infrastructure_km_sum', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_diesel', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_efuel', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_h2', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_battery', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_electrification', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_optimised_electrification', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_oe_to_battery', sa.Integer(), nullable=True))
    op.add_column('master_scenarios', sa.Column('infrastructure_km_oe_to_electrification', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_scenarios', 'infrastructure_km_oe_to_electrification')
    op.drop_column('master_scenarios', 'infrastructure_km_oe_to_battery')
    op.drop_column('master_scenarios', 'infrastructure_km_optimised_electrification')
    op.drop_column('master_scenarios', 'infrastructure_km_electrification')
    op.drop_column('master_scenarios', 'infrastructure_km_battery')
    op.drop_column('master_scenarios', 'infrastructure_km_h2')
    op.drop_column('master_scenarios', 'infrastructure_km_efuel')
    op.drop_column('master_scenarios', 'infrastructure_km_diesel')
    op.drop_column('master_scenarios', 'infrastructure_km_sum')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

