"""new tables project_content and other tables

Revision ID: 7e11cfa67e95
Revises: 998c7f554ad7
Create Date: 2022-04-07 10:29:35.392773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e11cfa67e95'
down_revision = '998c7f554ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nkv', sa.Integer(), nullable=True),
    sa.Column('nbs', sa.Boolean(), nullable=False),
    sa.Column('elektrification', sa.Boolean(), nullable=False),
    sa.Column('second_track', sa.Boolean(), nullable=False),
    sa.Column('third_track', sa.Boolean(), nullable=False),
    sa.Column('fourth_track', sa.Boolean(), nullable=False),
    sa.Column('curve', sa.Boolean(), nullable=False),
    sa.Column('platform', sa.Boolean(), nullable=False),
    sa.Column('junction_station', sa.Boolean(), nullable=False),
    sa.Column('number_junction_station', sa.Integer(), nullable=True),
    sa.Column('overtaking_station', sa.Boolean(), nullable=False),
    sa.Column('number_overtaking_station', sa.Integer(), nullable=True),
    sa.Column('double_occupancy', sa.Boolean(), nullable=False),
    sa.Column('block_increase', sa.Boolean(), nullable=False),
    sa.Column('flying_junction', sa.Boolean(), nullable=False),
    sa.Column('tunnel_structural_gauge', sa.Boolean(), nullable=False),
    sa.Column('increase_speed', sa.Boolean(), nullable=False),
    sa.Column('new_vmax', sa.Integer(), nullable=True),
    sa.Column('level_free_platform_entrance', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('railway__point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mifcode', sa.Integer(), nullable=True),
    sa.Column('bezeichnung', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('db_kuerzel', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('railway__point')
    op.drop_table('project_content')
    # ### end Alembic commands ###
