"""automatic migration

Revision ID: 8845ced9231b
Revises: aed38e851251
Create Date: 2022-08-07 14:27:05.975908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8845ced9231b'
down_revision = 'aed38e851251'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost', sa.Float(), nullable=True))
    # op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos')
    op.drop_index('railway_route_number_uindex', table_name='railway_route')
    op.drop_constraint('railway_route_end_point_fkey', 'railway_route', type_='foreignkey')
    op.drop_constraint('railway_route_start_point_fkey', 'railway_route', type_='foreignkey')
    op.create_foreign_key(None, 'railway_route', 'railway_points', ['end_point'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'railway_route', 'railway_points', ['start_point'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'railway_route', type_='foreignkey')
    op.drop_constraint(None, 'railway_route', type_='foreignkey')
    op.create_foreign_key('railway_route_start_point_fkey', 'railway_route', 'railway_points', ['start_point'], ['id'])
    op.create_foreign_key('railway_route_end_point_fkey', 'railway_route', 'railway_points', ['end_point'], ['id'])
    op.create_index('railway_route_number_uindex', 'railway_route', ['number'], unique=False)
    op.add_column('projects_contents', sa.Column('bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('projects_contents', 'bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cost')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

