"""corrected name

Revision ID: 90bfc9860abe
Revises: 7e11cfa67e95
Create Date: 2022-04-07 10:37:32.042862

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '90bfc9860abe'
down_revision = '7e11cfa67e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_point_start_id', sa.Integer(), nullable=True),
    sa.Column('id_point_end_id', sa.Integer(), nullable=True),
    sa.Column('superior_project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nkv', sa.Integer(), nullable=True),
    sa.Column('nbs', sa.Boolean(), nullable=False),
    sa.Column('elektrification', sa.Boolean(), nullable=False),
    sa.Column('second_track', sa.Boolean(), nullable=False),
    sa.Column('third_track', sa.Boolean(), nullable=False),
    sa.Column('fourth_track', sa.Boolean(), nullable=False),
    sa.Column('curve', sa.Boolean(), nullable=False),
    sa.Column('platform', sa.Boolean(), nullable=False),
    sa.Column('junction_station', sa.Boolean(), nullable=False),
    sa.Column('number_junction_station', sa.Integer(), nullable=True),
    sa.Column('overtaking_station', sa.Boolean(), nullable=False),
    sa.Column('number_overtaking_station', sa.Integer(), nullable=True),
    sa.Column('double_occupancy', sa.Boolean(), nullable=False),
    sa.Column('block_increase', sa.Boolean(), nullable=False),
    sa.Column('flying_junction', sa.Boolean(), nullable=False),
    sa.Column('tunnel_structural_gauge', sa.Boolean(), nullable=False),
    sa.Column('increase_speed', sa.Boolean(), nullable=False),
    sa.Column('new_vmax', sa.Integer(), nullable=True),
    sa.Column('level_free_platform_entrance', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('railway_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mifcode', sa.Integer(), nullable=True),
    sa.Column('streckennummer', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('from_km', sa.Integer(), nullable=True),
    sa.Column('to_km', sa.Integer(), nullable=True),
    sa.Column('electrified', sa.String(length=20), nullable=True),
    sa.Column('number_tracks', sa.Integer(), nullable=True),
    sa.Column('vmax', sa.String(length=20), nullable=True),
    sa.Column('type_of_transport', sa.String(length=20), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('railway_line')
    op.drop_table('project')
    op.drop_table('project_content')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('project_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nkv', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nbs', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('elektrification', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('second_track', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('third_track', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fourth_track', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('curve', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('junction_station', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('number_junction_station', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overtaking_station', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('number_overtaking_station', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('double_occupancy', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('block_increase', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('flying_junction', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tunnel_structural_gauge', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('increase_speed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('new_vmax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_free_platform_entrance', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='project_content_pkey')
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_point_start_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_point_end_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('superior_project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='project_pkey')
    )
    op.create_table('railway_line',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mifcode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('streckennummer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('electrified', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('number_tracks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vmax', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('type_of_transport', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='railway_line_pkey')
    )
    op.drop_table('railway_lines')
    op.drop_table('projects_contents')
    op.drop_table('projects')
    # ### end Alembic commands ###
