"""automatic migration

Revision ID: 916cd9e485f6
Revises: 1e6ecfbdffc4
Create Date: 2022-11-01 17:13:58.139015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '916cd9e485f6'
down_revision = '1e6ecfbdffc4'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('budgets_year_and_finve_uindex', table_name='budgets')
    # op.alter_column('railway_lines', 'voltage',
    #            existing_type=postgresql.DOUBLE_PRECISION(precision=53),
    #            comment=None,
    #            existing_comment='[kV]',
    #            existing_nullable=True)
    op.add_column('vehicles', sa.Column('vehicle_pattern_spnv', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_pattern_spfv', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_pattern_sgv', sa.Integer(), nullable=True))
    op.drop_constraint('vehicles_vehicle_pattern_id_h2_fkey', 'vehicles', type_='foreignkey')
    op.drop_constraint('vehicles_vehicle_pattern_id_electrical_fkey', 'vehicles', type_='foreignkey')
    op.drop_constraint('vehicles_vehicle_pattern_id_diesel_fkey', 'vehicles', type_='foreignkey')
    op.drop_constraint('vehicles_vehicle_pattern_id_battery_fkey', 'vehicles', type_='foreignkey')
    op.drop_constraint('vehicles_vehicle_pattern_id_efuel_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'vehicles_pattern', ['vehicle_pattern_sgv'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'vehicles_pattern', ['vehicle_pattern_spfv'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'vehicles_pattern', ['vehicle_pattern_spnv'], ['id'])
    op.drop_column('vehicles', 'vehicle_pattern_id_efuel')
    op.drop_column('vehicles', 'vehicle_pattern_id_electrical')
    op.drop_column('vehicles', 'vehicle_pattern_id_h2')
    op.drop_column('vehicles', 'vehicle_pattern_id_battery')
    op.drop_column('vehicles', 'vehicle_pattern_id_diesel')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_pattern_id_diesel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_pattern_id_battery', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_pattern_id_h2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_pattern_id_electrical', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_pattern_id_efuel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_vehicle_pattern_id_efuel_fkey', 'vehicles', 'vehicles_pattern', ['vehicle_pattern_id_efuel'], ['id'])
    op.create_foreign_key('vehicles_vehicle_pattern_id_battery_fkey', 'vehicles', 'vehicles_pattern', ['vehicle_pattern_id_battery'], ['id'])
    op.create_foreign_key('vehicles_vehicle_pattern_id_diesel_fkey', 'vehicles', 'vehicles_pattern', ['vehicle_pattern_id_diesel'], ['id'])
    op.create_foreign_key('vehicles_vehicle_pattern_id_electrical_fkey', 'vehicles', 'vehicles_pattern', ['vehicle_pattern_id_electrical'], ['id'])
    op.create_foreign_key('vehicles_vehicle_pattern_id_h2_fkey', 'vehicles', 'vehicles_pattern', ['vehicle_pattern_id_h2'], ['id'])
    op.drop_column('vehicles', 'vehicle_pattern_sgv')
    op.drop_column('vehicles', 'vehicle_pattern_spfv')
    op.drop_column('vehicles', 'vehicle_pattern_spnv')
    op.alter_column('railway_lines', 'voltage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='[kV]',
               existing_nullable=True)
    op.create_index('budgets_year_and_finve_uindex', 'budgets', ['budget_year', 'fin_ve'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

