"""table projects

Revision ID: 998c7f554ad7
Revises: 51fe948ca3a2
Create Date: 2022-04-06 19:46:29.131565

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = '998c7f554ad7'
down_revision = '51fe948ca3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_point_start_id', sa.Integer(), nullable=True),
    sa.Column('id_point_end_id', sa.Integer(), nullable=True),
    sa.Column('superior_project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    op.alter_column('railway_line', 'coordinates',
               existing_type=Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=False)
    op.drop_index('idx_railway_line_coordinates', table_name='railway_line')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_railway_line_coordinates', 'railway_line', ['coordinates'], unique=False)
    op.alter_column('railway_line', 'coordinates',
               existing_type=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('project')
    # ### end Alembic commands ###
