"""some more relations

Revision ID: 9a0b3cccefca
Revises: c76e621d1ee0
Create Date: 2022-04-07 11:22:10.511111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0b3cccefca'
down_revision = 'c76e621d1ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.create_foreign_key(None, 'projects', 'projects', ['superior_project_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'railway_points', ['id_point_end_id'], ['id'])
    op.add_column('projects_contents', sa.Column('project_number', sa.String(length=50), nullable=True))
    op.add_column('projects_contents', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('projects_contents', sa.Column('priority', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_contents', 'priority')
    op.drop_column('projects_contents', 'length')
    op.drop_column('projects_contents', 'project_number')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
