"""automatic migration

Revision ID: 9ea4aa49e6d3
Revises: f3caaa15c1b7
Create Date: 2022-08-17 15:53:11.434895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea4aa49e6d3'
down_revision = 'f3caaa15c1b7'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectcontent_to_railwaystations',
    sa.Column('projectcontent_id', sa.Integer(), nullable=True),
    sa.Column('railway_station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectcontent_id'], ['projects_contents.id'], ),
    sa.ForeignKeyConstraint(['railway_station_id'], ['railway_stations.id'], )
    )
    op.drop_table('projects_to_points')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('projects_to_points',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('railway_point_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='projects_to_points_project_id_fkey'),
    sa.ForeignKeyConstraint(['railway_point_id'], ['railway_points.id'], name='projects_to_points_railway_point_id_fkey')
    )
    op.drop_table('projectcontent_to_railwaystations')
    # ### end Alembic commands ###

