"""automatic migration

Revision ID: a58533c703dc
Revises: d2d33d31cdd8
Create Date: 2023-10-30 16:31:12.068087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58533c703dc'
down_revision = 'd2d33d31cdd8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('bks_cluster_number_fkey', 'bks', type_='foreignkey')
    op.drop_column('bks', 'cluster_number')
    op.add_column('bks_cluster', sa.Column('number', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'bks_cluster', ['number'])
    op.drop_constraint('bks_cluster_handlungsfeld_id_fkey', 'bks_cluster', type_='foreignkey')
    op.drop_column('bks_cluster', 'handlungsfeld_id')
    op.add_column('bks_handlungsfeld', sa.Column('number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'bks_handlungsfeld', ['number'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bks_handlungsfeld', type_='unique')
    op.drop_column('bks_handlungsfeld', 'number')
    op.add_column('bks_cluster', sa.Column('handlungsfeld_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bks_cluster_handlungsfeld_id_fkey', 'bks_cluster', 'bks_handlungsfeld', ['handlungsfeld_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'bks_cluster', type_='unique')
    op.drop_column('bks_cluster', 'number')
    op.add_column('bks', sa.Column('cluster_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bks_cluster_number_fkey', 'bks', 'bks_cluster', ['cluster_number'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

