"""automatic migration

Revision ID: b2ba78dd5dfe
Revises: c844d795bb76
Create Date: 2022-09-03 19:50:29.319103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ba78dd5dfe'
down_revision = 'c844d795bb76'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('projects_contents', sa.Column('use_capital_service_spfv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_maintenance_cost_spfv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_energy_cost_spfv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_capital_service_spnv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_maintenance_cost_spnv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_energy_cost_spnv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_capital_service_loco_sgv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_maintenance_cost_loco_sgv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_energy_cost_sgv', sa.Float(), nullable=True))
    op.add_column('projects_contents', sa.Column('use_change_traction_sgv', sa.Float(), nullable=True))
    op.drop_constraint('timetable_sections_timetable_ocp_id_fkey', 'timetable_sections', type_='foreignkey')
    op.create_foreign_key(None, 'timetable_sections', 'timetable_ocps', ['timetable_ocp_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('timetable_times_timetable_ocp_id_fkey', 'timetable_times', type_='foreignkey')
    op.create_foreign_key(None, 'timetable_times', 'timetable_ocps', ['timetable_ocp_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_times', type_='foreignkey')
    op.create_foreign_key('timetable_times_timetable_ocp_id_fkey', 'timetable_times', 'timetable_ocps', ['timetable_ocp_id'], ['id'])
    op.drop_constraint(None, 'timetable_sections', type_='foreignkey')
    op.create_foreign_key('timetable_sections_timetable_ocp_id_fkey', 'timetable_sections', 'timetable_ocps', ['timetable_ocp_id'], ['id'])
    op.drop_column('projects_contents', 'use_change_traction_sgv')
    op.drop_column('projects_contents', 'use_energy_cost_sgv')
    op.drop_column('projects_contents', 'use_maintenance_cost_loco_sgv')
    op.drop_column('projects_contents', 'use_capital_service_loco_sgv')
    op.drop_column('projects_contents', 'use_energy_cost_spnv')
    op.drop_column('projects_contents', 'use_maintenance_cost_spnv')
    op.drop_column('projects_contents', 'use_capital_service_spnv')
    op.drop_column('projects_contents', 'use_energy_cost_spfv')
    op.drop_column('projects_contents', 'use_maintenance_cost_spfv')
    op.drop_column('projects_contents', 'use_capital_service_spfv')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

