"""more m:n tables

Revision ID: b468bae3e5e4
Revises: 23657ae99b26
Create Date: 2022-04-07 12:16:40.725751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b468bae3e5e4'
down_revision = '23657ae99b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_to_lines',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('railway_lines_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['railway_lines_id'], ['railway_lines.id'], )
    )
    op.create_table('projects_to_points',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('railway_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['railway_point_id'], ['railway_points.id'], )
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_content_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('spent_cost_two_years_before', sa.Integer(), nullable=True),
    sa.Column('allowed_year_before', sa.Integer(), nullable=True),
    sa.Column('delegated_costs', sa.Integer(), nullable=True),
    sa.Column('planned_cost_this_year', sa.Integer(), nullable=True),
    sa.Column('planned_cost_next_year', sa.Integer(), nullable=True),
    sa.Column('planned_cost_following_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts_to_projects',
    sa.Column('project_content_id', sa.Integer(), nullable=True),
    sa.Column('text.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], ),
    sa.ForeignKeyConstraint(['text.id'], ['texts.id'], )
    )
    #op.drop_table('spatial_ref_sys')
    op.drop_table('budget')
    op.drop_table('text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='text_pkey')
    )
    op.create_table('budget',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_content_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spent_cost_two_years_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allowed_year_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delegated_costs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_cost_this_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_cost_next_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_cost_following_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_content_id'], ['projects_contents.id'], name='budget_project_content_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='budget_pkey')
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('texts_to_projects')
    op.drop_table('budgets')
    op.drop_table('projects_to_points')
    op.drop_table('projects_to_lines')
    op.drop_table('texts')
    # ### end Alembic commands ###
