"""automatic migration

Revision ID: b9f6a5c2cf8b
Revises: acc6b149f1f3
Create Date: 2022-11-20 14:57:08.578291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'b9f6a5c2cf8b'
down_revision = 'acc6b149f1f3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_tunnels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_number_id', sa.Integer(), nullable=True),
    sa.Column('richtung', sa.Integer(), nullable=True),
    sa.Column('von_km_i', sa.BigInteger(), nullable=True),
    sa.Column('bis_km_i', sa.BigInteger(), nullable=True),
    sa.Column('von_km_l', sa.String(length=100), nullable=True),
    sa.Column('bis_km_l', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.ForeignKeyConstraint(['route_number_id'], ['railway_route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_railway_tunnels_geometry', 'railway_tunnels', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('budgets_year_and_finve_uindex', table_name='budgets')
    op.add_column('railway_lines', sa.Column('tunnel_id', sa.Integer(), nullable=True))
    # op.alter_column('railway_lines', 'voltage',
    #            existing_type=postgresql.DOUBLE_PRECISION(precision=53),
    #            comment=None,
    #            existing_comment='[kV]',
    #            existing_nullable=True)
    op.create_foreign_key(None, 'railway_lines', 'railway_tunnels', ['tunnel_id'], ['id'], ondelete='SET NULL')
    op.drop_column('railway_lines', 'tunnel')
    op.drop_column('railway_lines', 'tunnel_name')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('railway_lines', sa.Column('tunnel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('railway_lines', sa.Column('tunnel', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'railway_lines', type_='foreignkey')
    op.alter_column('railway_lines', 'voltage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='[kV]',
               existing_nullable=True)
    op.drop_column('railway_lines', 'tunnel_id')
    op.create_index('budgets_year_and_finve_uindex', 'budgets', ['budget_year', 'fin_ve'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index('idx_railway_tunnels_geometry', table_name='railway_tunnels', postgresql_using='gist', postgresql_ops={})
    op.drop_table('railway_tunnels')
    # ### end Alembic commands ###

