"""automatic migration

Revision ID: c30b217b586f
Revises: bafc4e04239f
Create Date: 2023-12-15 16:59:00.570645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30b217b586f'
down_revision = 'bafc4e04239f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('budgets', sa.Column('cost_estimate_actual_891_72', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('spent_two_years_previous_891_72', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('allowed_previous_year_891_72', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('spending_residues_891_72', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('year_planned_891_72', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('next_years_891_72', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'next_years_891_72')
    op.drop_column('budgets', 'year_planned_891_72')
    op.drop_column('budgets', 'spending_residues_891_72')
    op.drop_column('budgets', 'allowed_previous_year_891_72')
    op.drop_column('budgets', 'spent_two_years_previous_891_72')
    op.drop_column('budgets', 'cost_estimate_actual_891_72')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

