"""removed foreign keys in project

Revision ID: c3d166db9da3
Revises: b468bae3e5e4
Create Date: 2022-04-14 23:25:40.090432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d166db9da3'
down_revision = 'b468bae3e5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('projects_id_point_end_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_id_point_start_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'id_point_start_id')
    op.drop_column('projects', 'id_point_end_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('id_point_end_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('id_point_start_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_id_point_start_id_fkey', 'projects', 'railway_points', ['id_point_start_id'], ['id'])
    op.create_foreign_key('projects_id_point_end_id_fkey', 'projects', 'railway_points', ['id_point_end_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
