"""automatic migration

Revision ID: c71c21e6a593
Revises: 3692d09a8444
Create Date: 2023-10-30 16:32:54.021193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71c21e6a593'
down_revision = '3692d09a8444'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bks_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('report_process', sa.Text(), nullable=True),
    sa.Column('review_1_start', sa.Text(), nullable=True),
    sa.Column('review_1_done', sa.Text(), nullable=True),
    sa.Column('review_1_next', sa.Text(), nullable=True),
    sa.Column('review_1_status', sa.String(length=255), nullable=True),
    sa.Column('review_1_changed_aim', sa.Boolean(), nullable=True),
    sa.Column('cluster_number', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cluster_number'], ['bks_cluster.number'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    op.drop_table('bks')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('report_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_process', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_1_start', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_1_done', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_1_next', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_1_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('review_1_changed_aim', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cluster_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cluster_number'], ['bks_cluster.number'], name='bks_cluster_number_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='bks_pkey')
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('bks_action')
    # ### end Alembic commands ###

