"""automatic migration

Revision ID: cebb4975b1cd
Revises: 42e346cb4d2a
Create Date: 2022-09-10 22:08:29.659284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebb4975b1cd'
down_revision = '42e346cb4d2a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('vehicles_pattern', sa.Column('vehicle_cost_km', sa.Float(), nullable=True))
    op.add_column('vehicles_pattern', sa.Column('energy_cost_per_km', sa.Float(), nullable=True))
    op.add_column('vehicles_pattern', sa.Column('energy_cost_stop', sa.Float(), nullable=True))
    op.add_column('vehicles_pattern', sa.Column('co2_km', sa.Float(), nullable=True, comment='g/km'))
    op.add_column('vehicles_pattern', sa.Column('co2_stop', sa.Float(), nullable=True, comment='g/stop'))
    op.add_column('vehicles_pattern', sa.Column('emission_km', sa.Float(), nullable=True, comment='€/km'))
    op.add_column('vehicles_pattern', sa.Column('emission_stop', sa.Float(), nullable=True, comment='€/stop'))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles_pattern', 'emission_stop')
    op.drop_column('vehicles_pattern', 'emission_km')
    op.drop_column('vehicles_pattern', 'co2_stop')
    op.drop_column('vehicles_pattern', 'co2_km')
    op.drop_column('vehicles_pattern', 'energy_cost_stop')
    op.drop_column('vehicles_pattern', 'energy_cost_per_km')
    op.drop_column('vehicles_pattern', 'vehicle_cost_km')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

