"""automatic migration

Revision ID: d2d33d31cdd8
Revises: 63a4584f24a2
Create Date: 2023-10-30 16:28:22.850312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d33d31cdd8'
down_revision = '63a4584f24a2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('bks', sa.Column('cluster_number', sa.Integer(), nullable=True))
    op.drop_constraint('bks_cluster_id_fkey', 'bks', type_='foreignkey')
    op.create_foreign_key(None, 'bks', 'bks_cluster', ['cluster_number'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('bks', 'cluster_id')
    op.add_column('bks_cluster', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('bks_cluster', 'number')
    op.add_column('bks_handlungsfeld', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('bks_handlungsfeld', 'number')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bks_handlungsfeld', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bks_handlungsfeld', 'text')
    op.add_column('bks_cluster', sa.Column('number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('bks_cluster', 'text')
    op.add_column('bks', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bks', type_='foreignkey')
    op.create_foreign_key('bks_cluster_id_fkey', 'bks', 'bks_cluster', ['cluster_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('bks', 'cluster_number')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

