"""automatic migration

Revision ID: d332db131cf5
Revises: 12f5a6a40c66
Create Date: 2022-09-23 13:00:24.025583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd332db131cf5'
down_revision = '12f5a6a40c66'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('projects', sa.Column('superior_project_content_id', sa.Integer(), nullable=True))
    op.drop_constraint('projects_superior_project_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'projects_contents', ['superior_project_content_id'], ['id'])
    op.drop_column('projects', 'superior_project_id')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('superior_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_superior_project_id_fkey', 'projects', 'projects', ['superior_project_id'], ['id'])
    op.drop_column('projects', 'superior_project_content_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

