"""empty message

Revision ID: e0dc7f36f944
Revises: 55c913d40988
Create Date: 2023-01-21 14:07:50.038441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0dc7f36f944'
down_revision = '55c913d40988'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('budgets_year_and_finve_uindex', table_name='budgets')
    # op.alter_column('railway_lines', 'voltage',
    #            existing_type=postgresql.DOUBLE_PRECISION(precision=53),
    #            comment=None,
    #            existing_comment='[kV]',
    #            existing_nullable=True)
    op.add_column('route_traingroups', sa.Column('master_scenario_id', sa.Integer(), nullable=True))
    op.drop_constraint('route_traingroups_master_scenario_fkey', 'route_traingroups', type_='foreignkey')
    op.create_foreign_key(None, 'route_traingroups', 'master_scenarios', ['master_scenario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('route_traingroups', 'master_scenario')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_traingroups', sa.Column('master_scenario', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route_traingroups', type_='foreignkey')
    op.create_foreign_key('route_traingroups_master_scenario_fkey', 'route_traingroups', 'master_scenarios', ['master_scenario'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('route_traingroups', 'master_scenario_id')
    op.alter_column('railway_lines', 'voltage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='[kV]',
               existing_nullable=True)
    op.create_index('budgets_year_and_finve_uindex', 'budgets', ['budget_year', 'fin_ve'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

