"""automatic migration

Revision ID: ee81fbf194bc
Revises: 1e1eaf409857
Create Date: 2022-06-11 16:16:25.815839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee81fbf194bc'
down_revision = '1e1eaf409857'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_contents', sa.Column('planned_maintenance_cost_bvwp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_contents', 'planned_maintenance_cost_bvwp')
    # ### end Alembic commands ###

